receivers:
  otlp:
    protocols:
      grpc:
        endpoint: 0.0.0.0:4317
      http:
        endpoint: 0.0.0.0:4318

processors:
  batch:
    timeout: 100ms

exporters:
  clickhouse:
    endpoint: tcp://clickhouse:9000/?database=signoz_traces
    logs_table_name: logs
    traces_table_name: signoz_index_v2
    metrics_table_name: signoz_metrics_v2

service:
  pipelines:
    traces:
      receivers: [otlp]
      processors: [batch]
      exporters: [clickhouse]
    metrics:
      receivers: [otlp]
      processors: [batch]
      exporters: [clickhouse]
    logs:
      receivers: [otlp]
      processors: [batch]
      exporters: [clickhouse]
